/**
 * The S4.1 / S4.2 / S4.3 acceptance test: usage on screen, an automatic title,
 * and a search box that filters the left column.
 *
 * Like `chat.spec.ts` this one needs a **real** local model, because the two
 * things it is proving only exist after a provider has answered: token counts
 * come from the provider's own usage report, and a title is generated by the
 * first member's model. So the whole file is **skipped when
 * `http://localhost:11434/v1/models` does not answer**, and the skip is explicit
 * in the report rather than a silent pass.
 *
 * The UI is switched to **English** here rather than to Chinese (which
 * `chat.spec.ts` uses for its screenshot): the usage assertion reads rendered
 * copy — `12.4k tokens` — because that string is the acceptance criterion, and a
 * language-independent version of it would be asserting on a `data-` attribute
 * instead of on what the user actually sees. Every other assertion is on a
 * `data-testid`. No Chinese appears in this file (CLAUDE.md rule #1).
 */
import { mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { expect, test, type ElectronApplication, type Page } from '@playwright/test'
import {
  createUserDataDir,
  launchWitena,
  locale,
  openProviderSettings,
  removeUserDataDir,
  repoRoot
} from './helpers'

/** Serial: the tests share one app and each builds on the last one's data. */
test.describe.configure({ mode: 'serial' })

const SHOTS_DIR = process.env['WITENA_SHOTS_DIR'] ?? join(repoRoot, 'test-results', 'shots')

/** The artboard size, so the screenshot lines up with the mockup. */
const WINDOW_SIZE = { width: 1440, height: 900 }

/** Ollama's OpenAI-compatible endpoint, the same URL the `ollama` preset stores. */
const OLLAMA_MODELS_URL = 'http://localhost:11434/v1/models'

/** Small, fast, and present on any machine that has pulled anything at all. */
const MODEL_ID = 'qwen2.5:1.5b'

/** A cold Ollama has to load the weights before the first token appears. */
const COLD_START_MS = 90_000

/** A title is generated after the run finishes, and needs its own model call. */
const TITLE_MS = 30_000

/** The word the second chat is built around, so the search has one clear hit. */
const NEEDLE = 'zebra'

const en = locale('en')

let app: ElectronApplication | undefined
let window: Page
let userDataDir: string
let ollamaUp = false

async function probeOllama(): Promise<boolean> {
  try {
    const response = await fetch(OLLAMA_MODELS_URL, { signal: AbortSignal.timeout(2_000) })
    return response.ok
  } catch {
    return false
  }
}

/** Pins the window size and the UI language, so the copy assertions are stable. */
async function prepare(): Promise<void> {
  await app?.evaluate(({ BrowserWindow }, size) => {
    const [main] = BrowserWindow.getAllWindows()
    main?.setContentSize(size.width, size.height)
  }, WINDOW_SIZE)

  await window.getByTestId('nav-settings').click()
  await window.getByTestId('lang-en').click()
  await expect(window.getByTestId('page-settings')).toHaveText(en.settings.title)
}

const agentMessages = () => window.locator('[data-testid="message-item"][data-sender="agent"]')

/** Creates a chat, makes sure it has a member, and returns nothing. */
async function newChat(): Promise<void> {
  const before = await window.getByTestId('chat-item').count()
  await window.getByTestId('chats-new').click()
  await expect(window.getByTestId('chat-item')).toHaveCount(before + 1)
  await expect(window.getByTestId('composer-input')).toBeEnabled()

  if ((await window.getByTestId('member-row').count()) === 0) {
    await window.getByTestId('member-add').click()
    await window.getByTestId('member-candidate').first().click()
    await expect(window.getByTestId('member-row')).toHaveCount(1)
  }
}

/** Sends a question and waits for the one reply it produces to finish. */
async function ask(question: string): Promise<void> {
  const before = await agentMessages().count()
  await window.getByTestId('composer-input').fill(question)
  await window.getByTestId('composer-input').press('Enter')

  const reply = agentMessages().nth(before)
  await expect(reply).toHaveAttribute('data-status', 'done', { timeout: COLD_START_MS })
}

test.beforeAll(async () => {
  ollamaUp = await probeOllama()
  if (!ollamaUp) return

  userDataDir = createUserDataDir()
  ;({ app, window } = await launchWitena(userDataDir))
  mkdirSync(SHOTS_DIR, { recursive: true })
  await prepare()
})

test.afterAll(async () => {
  await app?.close()
  if (userDataDir) removeUserDataDir(userDataDir)
})

test('adds the local Ollama provider with one small model', async () => {
  test.skip(!ollamaUp, `${OLLAMA_MODELS_URL} did not answer; the polish spec needs a local model.`)

  await openProviderSettings(window)
  await window.getByTestId('providers-add').click()
  await window.getByTestId('preset-ollama').click()
  await window.getByTestId('provider-add-model').click()
  await window.getByTestId('provider-add-model-input').fill(MODEL_ID)
  await window.getByTestId('provider-add-model-input').press('Enter')
  await window.getByTestId('provider-save').click()
  await expect(window.getByTestId('provider-card')).toHaveCount(1)
})

test('shows the chat token usage in the header and per member (S4.1)', async () => {
  test.skip(!ollamaUp, 'no local Ollama')
  test.setTimeout(COLD_START_MS + 60_000)

  await window.getByTestId('nav-chats').click()
  await newChat()

  // Nothing has been said, so there is no claim to make about tokens yet.
  await expect(window.getByTestId('chat-usage')).toHaveCount(0)

  await ask('Reply with the single word hello')

  // `12.4k tokens`, or `842 tokens` on a short exchange.
  const usage = window.getByTestId('chat-usage')
  await expect(usage).toBeVisible()
  await expect(usage).toHaveText(/\d[\d.]*k? tokens/)

  // The member row's placeholder em dash has been replaced by a real count.
  const memberUsage = window.getByTestId('member-usage').first()
  await expect(memberUsage).toHaveText(/\d[\d.]*k?/)
  await expect(memberUsage).not.toHaveAttribute('data-tokens', '0')
})

test('names the chat automatically once the first reply is in (S4.3)', async () => {
  test.skip(!ollamaUp, 'no local Ollama')
  test.setTimeout(TITLE_MS + 30_000)

  const title = window.getByTestId('chat-item-title').first()
  // Either the model produced a title or the fallback did; in both cases the
  // placeholder is gone. Ollama is asked *after* the run finishes, so this is
  // the one assertion that has to wait for something the previous test did not.
  await expect(title).not.toHaveText(en.chat.newChat, { timeout: TITLE_MS })
  await expect(title).not.toBeEmpty()

  await window.screenshot({ path: join(SHOTS_DIR, 'polish.png') })
})

test('filters the chat list from the search box (S4.3)', async () => {
  test.skip(!ollamaUp, 'no local Ollama')
  test.setTimeout(COLD_START_MS + 60_000)

  await newChat()
  await ask(`What colour is a ${NEEDLE}? Answer in three words.`)
  await expect(window.getByTestId('chat-item')).toHaveCount(2)

  const search = window.getByTestId('chats-search')
  await search.fill(NEEDLE)

  // Debounced by 200 ms, then one chat is left: the one whose question had the
  // word in it. (Its generated title may well contain it too; either way it is
  // the only match.)
  await expect(window.getByTestId('chat-item')).toHaveCount(1, { timeout: 10_000 })

  // A word in neither chat empties the list and shows the search empty state.
  await search.fill('quagmire-that-nobody-typed')
  await expect(window.getByTestId('chat-item')).toHaveCount(0, { timeout: 10_000 })
  await expect(window.getByText(en.chat.searchEmptyTitle)).toBeVisible()

  // Clearing the box brings both back.
  await search.fill('')
  await expect(window.getByTestId('chat-item')).toHaveCount(2, { timeout: 10_000 })
})
